main: io.github.spaery.simplerhomes.SimplerHomes
name: SimplerHomes
author: Spaery
version: 1.1.1
api-version: 1.19

commands:
  home:
    description: Teleport to the requested home location
    usage: /home (NameOfHome)
  homes:
    description: View a list of set homes
    usage: /homes
  sethome:
    description: Create a home to return to when executing "/home" command
    usage: /sethome (NameOfHome)
  delhome:
    description: Delete the specified home
    usage: /delhome (NameOfHome)